@echo off
setlocal enabledelayedexpansion
title Push WhatsApp MCP to GitHub

set "MCP_DIR=%~dp0..\"
pushd "%MCP_DIR%" >nul

cls
echo ============================================
echo   Push WhatsApp MCP to GitHub
echo ============================================
echo.
echo This will:
echo   1. git init + stage + commit (skipping secrets via .gitignore)
echo   2. Open github.com/new in your browser
echo   3. Wait for you to create the repo + paste the URL
echo   4. Push the code up
echo.
pause

REM ---- 1) check git is installed
where git >nul 2>nul
if errorlevel 1 (
    echo ERROR: Git is not installed or not on PATH.
    echo Install Git for Windows: https://git-scm.com/download/win
    pause
    popd
    exit /b 1
)

REM ---- 2) check git is configured (name + email)
git config --global user.email >nul 2>nul
if errorlevel 1 (
    echo.
    echo Git is not configured yet. Let's set it up:
    set /p GIT_NAME="Enter your name (e.g. Steve Meng): "
    set /p GIT_EMAIL="Enter your email (for git commits): "
    git config --global user.name "!GIT_NAME!"
    git config --global user.email "!GIT_EMAIL!"
)

REM ---- 3) git init (if not already a repo)
if not exist ".git" (
    echo.
    echo === Step 1: git init ===
    git init -b main >nul
    if errorlevel 1 (
        echo ERROR: git init failed.
        pause
        popd
        exit /b 1
    )
    echo OK initialised.
) else (
    echo Already a git repo, skipping init.
)

REM ---- 4) stage files
echo.
echo === Step 2: stage files ===
git add .
echo.
echo Files about to be committed:
git status --short
echo.
echo Make sure NONE of these sensitive files appear above:
echo   auth\          (WhatsApp credentials)
echo   data\          (your message cache)
echo   api-key.txt    (your OpenAI key)
echo   node_modules\  (huge, will be regenerated by npm install)
echo.
echo If anything sensitive IS listed, press N to abort and check .gitignore.
echo.
set /p PROCEED="Continue with commit? (Y/N): "
if /i not "!PROCEED!"=="Y" (
    echo Aborted. Nothing pushed.
    pause
    popd
    exit /b 0
)

REM ---- 5) commit (skip if nothing to commit)
echo.
echo === Step 3: commit ===
git diff --cached --quiet
if errorlevel 1 (
    git commit -m "Initial commit: WhatsApp MCP for Claude"
    if errorlevel 1 (
        echo ERROR: commit failed.
        pause
        popd
        exit /b 1
    )
) else (
    echo Nothing new to commit (already committed).
)

REM ---- 6) open GitHub in browser
echo.
echo === Step 4: create the repo on GitHub ===
echo Opening https://github.com/new in your browser...
start "" "https://github.com/new"
echo.
echo In the browser:
echo   1. Repository name: anything you want (e.g. whatsapp-mcp)
echo   2. Public or Private: your choice
echo   3. DO NOT tick "Initialize with README/.gitignore/LICENSE"
echo      (we already have those)
echo   4. Click "Create repository"
echo   5. On the next page, copy the HTTPS URL.
echo      Looks like:  https://github.com/yourname/whatsapp-mcp.git
echo.
set /p REPO_URL="Paste the repo URL here and press Enter: "

if "!REPO_URL!"=="" (
    echo No URL provided. Aborted.
    pause
    popd
    exit /b 1
)

REM ---- 7) wire remote + push
echo.
echo === Step 5: push to GitHub ===
git remote remove origin >nul 2>nul
git remote add origin "!REPO_URL!"

REM Make sure branch is named main
git branch -M main

echo Pushing...
git push -u origin main
if errorlevel 1 (
    echo.
    echo ============================================
    echo   Push failed.
    echo ============================================
    echo Possible reasons:
    echo   - GitHub sign-in popup needed your attention (check the browser)
    echo   - Wrong repo URL pasted
    echo   - You used the SSH URL but don't have an SSH key set up
    echo     (Try the HTTPS URL instead - github.com/yourname/repo.git)
    echo   - The repo on GitHub already has commits
    echo     (Recreate it empty, or use:  git push -u origin main --force )
    echo.
    pause
    popd
    exit /b 1
)

echo.
echo ============================================
echo   SUCCESS. Code is on GitHub.
echo.
echo   !REPO_URL!
echo ============================================
echo.
echo Anyone you share the URL with can clone + install with:
echo   git clone !REPO_URL!
echo   cd whatsapp-mcp
echo   windows\install.bat
echo.
pause
popd
